run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
linters-settings:
  revive:
    rules:
      - name: dot-imports
        severity: warning
        disabled: true
