name: "Set up Docker Network and connect to the registry"
description: "Set up Docker Network and connect to the registry"

runs:
  using: "composite"
  steps:  
    # - name: Add the registry config to the nodes
    #   shell: bash
    #   run:  |
    #     REGISTRY_DIR="/etc/containerd/certs.d/${REGISTRY_ADDRESS}"
    #     for node in $(kind get nodes); do
    #       docker exec "${node}" mkdir -p "${REGISTRY_DIR}"
    #       cat <<EOF | docker exec -i "${node}" cp /dev/stdin "${REGISTRY_DIR}/hosts.toml"
    #     [host."http://${REGISTRY_ADDRESS}"]
    #     EOF
    #     done

    - name: Connect the registry to the cluster network
      shell: bash
      run:  |
        # Connect the registry to the cluster network if not already connected
        # This allows kind to bootstrap the network but ensures they're on the same

        docker network connect kind-cluster $REGISTRY_NAME
        # if [ "$(docker inspect -f='{{json .NetworkSettings.Networks.kind}}' "${REGISTRY_NAME}")" = 'null' ]; then
        #   docker network connect kind-cluster $REGISTRY_NAME
        # fi
