apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deploymentconfigs.apps.openshift.io
spec:
  group: apps.openshift.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: Namespaced
  names:
    plural: deploymentconfigs
    singular: deploymentconfig
    kind: DeploymentConfig
    shortNames:
      - dc
