apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagestreams.image.openshift.io
spec:
  group: image.openshift.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: Namespaced
  names:
    plural: imagestreams
    singular: imagestream
    kind: ImageStream
    shortNames:
      - is
