apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 0.0.0.0:8080
    webhook:
      port: 9443
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-operator
    app.kubernetes.io/part-of: opendatahub
  name: opendatahub-operator-manager-config
