apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendatahub-operator-controller-manager
  namespace: opendatahub-operator-system
spec:
  template:
    spec:
      containers:
        - image: controller
          name: manager