apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opendatahub-operator-system
resources:
  - ../../base
patchesStrategicMerge:
  - img_patch.yaml
  - res_patch.yaml
  - user_patch.yaml
images:
  - name: controller
    newName: quay.io/opendatahub/opendatahub-operator
    newTag: main