apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: opendatahubapplications-controller
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 256Mi