name: Build images for Main branch
on:
  push:
    branches:
      - main
      - incubation
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  IMAGE_REPO_ODHO: opendatahub-operator
  QUAY_ORG: apratap
  QUAY_ID: ${{ secrets.QUAY_ID }}
  QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
  SOURCE_BRANCH: main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v4
      - name: Generate Tag
        shell: bash
        id: tags
        run: |
          commit_sha=${{ github.event.after }}
          tag=${{ steps.extract_branch.outputs.branch }}-${commit_sha:0:7}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: Build Image
        uses: ./.github/actions/build
        env:
          IMG: quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_REPO_ODHO }}:${{ steps.tags.outputs.tag }}
          TARGET_IMAGE_TAG: ${{ steps.tags.outputs.tag }}
        with:
          OVERWRITE: true
          IMAGE_REPO: ${{ env.IMAGE_REPO_ODHO }}
          DOCKERFILE: ./Dockerfiles/Dockerfile
          GH_REPO: ${{ github.repository }}
      - name: Tag latest
        shell: bash
        env:
          IMG: quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_REPO_ODHO }}
          NEWEST_TAG: ${{ steps.tags.outputs.tag }}
        run: |
          podman tag ${IMG}:${NEWEST_TAG} ${IMG}:${{ steps.extract_branch.outputs.branch }}
          podman push ${IMG}:${{ steps.extract_branch.outputs.branch }}
          podman tag ${IMG}:${NEWEST_TAG} ${IMG}:${{ steps.extract_branch.outputs.branch }}
          podman push ${IMG}:${{ steps.extract_branch.outputs.branch }}
