name: Build images for Main branch
on:
  push:
    branches:
      - main
      - incubation
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  IMAGE_NAME: opendatahub-operator
  QUAY_ORG: opendatahub
  QUAY_ID: ${{ secrets.QUAY_ID }}
  QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
  SOURCE_BRANCH: main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate commit tag
        shell: bash
        id: tags
        run: |
          commit_sha=${{ github.event.after }}
          tag=${{ steps.extract_branch.outputs.branch }}-${commit_sha:0:7}
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Login to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.QUAY_ID }}
          password: ${{ env.QUAY_TOKEN }}
          registry: quay.io

      - name: Build the image
        env:
          IMAGE: quay.io/${{ env.QUAY_ORG }}/${{ inputs.IMAGE_NAME }}:${{ steps.tags.outputs.tag }}
          COMMIT_TAG: ${{ steps.tags.outputs.tag }}
        run:  |
          podman build --file ./Dockerfiles/Dockerfile --build-arg TARGETOS=linux --build-arg TARGETARCH=arm64 --label quay.expires-after=90d \
          --label git-sha=$GITHUB_SHA --no-cache --platform linux/arm64 --manifest {{ env.$IMAGE }} .

      - name: Push the image
        run: |
          podman manifest push $IMAGE_NAME:latest docker://quay.io/${{ secrets.QUAY_ORG }}/$IMAGE_NAME:${{ COMMIT_TAG }}
          podman manifest push $IMAGE_NAME:latest docker://quay.io/${{ secrets.QUAY_ORG }}/$IMAGE_NAME:latest
          