name: Install Operator-SDK

on:
  pull_request:
    branches:
      - main
      - "incubation"
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'
  push:
    branches:
      - main
      - "incubation"
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-operator-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Operator-SDK
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/v${{ env.OPERATOR_SDK_VERSION}}/download/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64
          sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
        shell: bash
        env:
          OPERATOR_SDK_VERSION: 1.24.1

      - name: Verify Operator-SDK installation
        run: operator-sdk version

      - name: Build Operator Bundle
        run: |
          # Pull the Docker image from registry
          podman pull quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
       
          # Create an Operator Bundle using the image
          operator-sdk bundle create quay.io/${{ env.QUAY_ORG }}/${{ env.BUNDLE_IMAGE_NAME }}:${{ env.IMAGE_TAG }} --image quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --overwrite
