name: e2e Tests

on:
  pull_request:
    branches:
      - main
      - "incubation"
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'
  push:
    branches:
      - main
      - "incubation"
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  QUAY_ORG: apratap
  BUNDLE_IMAGE_NAME: opendatahub-operator-bundle
  IMAGE_NAME: opendatahub-operator
  IMAGE_TAG: pr-4

jobs:
  kubernetes-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Operator SDK
        shell: bash
        run:  |
          # curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v${{ env.OPERATOR_SDK_VERSION }}/operator-sdk-v${{ env.OPERATOR_SDK_VERSION }}-x86_64-linux-gnu
          # sudo chmod +x operator-sdk-v${{ env.OPERATOR_SDK_VERSION }}-x86_64-linux-gnu
          # sudo mv operator-sdk-v${{ env.OPERATOR_SDK_VERSION }}-x86_64-linux-gnu /usr/local/bin/operator-sdk
          # ls /usr/local/bin/
          # echo /usr/local/bin/operator-sdk >> $GITHUB_PATH
          # echo $PATH
          curl -LO https://github.com/operator-framework/operator-sdk/releases/latest/download/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64
          sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
        env:
          OPERATOR_SDK_VERSION: 1.24.1

      - name: Verify Operator-SDK installation
        run: operator-sdk version

      - name: Build Operator Bundle
        run: |
          # Pull the Docker image from registry
          podman pull quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
       
      #     # Create an Operator Bundle using the image
      #     #operator-sdk bundle create quay.io/${{ env.QUAY_ORG }}/${{ env.BUNDLE_IMAGE_NAME }}:${{ env.IMAGE_TAG }} --image quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --overwrite
          
      #     # Set the bundle directory
      #     #export BUNDLE_DIR=./bundle

      #     #Build the bundle image using operator-sdk
      #     #operator-sdk bundle create $BUNDLE_DIR --metadata --image $quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #     #Verify bundle
      #     # operator-sdk bundle validate $BUNDLE_DIR

      - name: Setup and start KinD cluster
        uses: ./.github/actions/kind

      - name: Verify KinD
        run:  kubectl get nodes

      - name: Load Image in KinD cluster
        run: |
          kind load docker-image ${{ env.QUAY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Deploy Operatorhub operator bundle
        id: deploy
        run: |
          echo Deploying Operatorhub operator
          IMG="${REGISTRY_ADDRESS}"/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          make deploy -e IMG="${IMG}"
          kubectl wait --timeout=120s --for=condition=Available=true deployment -n openshift-operators opendatahub-operator-manager

      - name: Run e2e tests
        run: |
          make e2e-test
