name: Unit Tests
on:
  pull_request:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.x'
      - name: Run Unit Tests
        run: make unit-test